apiVersion: batch/v1
kind: Job
metadata:
  name: restore
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: restore
          envFrom:
          - secretRef:
              name: sosialmedia-mysql-secret
          image: mysql:5.6
          command: [sh, -c]
          args: ["-c", "apt-get update -y && apt-get install wget -y",  "wget https://raw.githubusercontent.com/Tsubekti/sosial-media/master/dump.sql", "mysql -h staging-database.cazjaeor2sa8.ap-southeast-1.rds.amazonaws.com -u admin -p123456789 -e 'CREATE DATABASE dbsosmed'", "mysql -h staging-database.cazjaeor2sa8.ap-southeast-1.rds.amazonaws.com -u admin -p123456789 dbsosmed < dump.sql"]