apiVersion: apps/v1
kind: Deployment
metadata:
  name: sosmed
  labels:
    app: sosmed
spec:
  selector:
    matchLabels:
      app: sosmed
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: sosmed
        tier: frontend
    spec:
      containers:
      - image: tsubekti/sosmed:v10
        name: sosmed
        env:
          - name: DB_HOST
            valueFrom:
              secretKeyRef:
                name: sosmed-secret
                key: DB_HOST
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: sosmed-secret
                key: mysql_user
          - name: DB_PASS
            valueFrom:
              secretKeyRef:
                name: sosmed-secret
                key: mysql_user_password
          - name: DB_NAME
            valueFrom:
              secretKeyRef:
                name: sosmed-secret
                key: mysql_db
        ports:
        - containerPort: 80
          name: sosmed
      volumes:
      - name: sosmed-persistent-storage
        persistentVolumeClaim:
          claimName: sosmed-prod-pvc