apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
        tier: frontend
    spec:
      containers:
      - image: tsubekti/wordpress:v4
        name: wordpress
        env:
          - name:  WORDPRESS_DB_HOST
            valueFrom:
              secretKeyRef:
                name: wp-secret
                key: WORDPRESS_DB_HOST
          - name:  WORDPRESS_DB_USER
            valueFrom:
              secretKeyRef:
                name:  wp-secret
                key:  WORDPRESS_DB_USER
          - name:  WORDPRESS_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name:  wp-secret
                key:  WORDPRESS_DB_PASSWORD
          - name:  WORDPRESS_DB_NAME
            valueFrom:
              secretKeyRef:
                name:  wp-secret
                key:  WORDPRESS_DB_NAME
        ports:
        - containerPort: 80
          name: wordpress
        volumeMounts:
        - name: wordpress-persistent-storage
          mountPath: /var/www/html
      volumes:
      - name: wordpress-persistent-storage
        persistentVolumeClaim:
          claimName: wp-pv-claim