apiVersion: v1
kind: Secret
metadata:
  name: wp-secret
type: Opaque
stringData:
  WORDPRESS_DB_HOST : "database-staging"
  WORDPRESS_DB_USER : "admin"
  WORDPRESS_DB_PASSWORD: "123456789"
  WORDPRESS_DB_NAME : "wordpress"
