kind: Service
apiVersion: v1
metadata:
  name: wordpress-service
spec:
  selector:
    app: wordpress
    tier: frontend
  type: LoadBalancer
  ports:
  - name: wordpress
    port:  80
    targetPort: 80
    protocol: TCP
