apiVersion: batch/v1
kind: Job
metadata:
  name: create-db
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: create-db
          envFrom:
          - secretRef:
              name: wp-secret
          image: mysql:5.6
          command: [sh, -c]
          args: ["-c", "mysql -h staging-database.cazjaeor2sa8.ap-southeast-1.rds.amazonaws.com -u admin -p123456789 -e 'CREATE DATABASE wordpress'"]